// <auto-generated />
using System;
using EcoClean.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EcoClean.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240627213333_AddMorador")]
    partial class AddMorador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoClean.Models.CaminhaoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CoordenadaX")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CoordenadaY")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DATE");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE");

                    b.HasKey("Id");

                    b.ToTable("Caminhao", (string)null);
                });

            modelBuilder.Entity("EcoClean.Models.ColetaModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CaminhaoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DATE");

                    b.Property<long>("EnderecoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("PrevisaoHorario")
                        .HasColumnType("DATE");

                    b.Property<long>("RotaId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE");

                    b.HasKey("Id");

                    b.HasIndex("CaminhaoId");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("RotaId");

                    b.ToTable("Coleta", (string)null);
                });

            modelBuilder.Entity("EcoClean.Models.ColetaTipoResiduoModel", b =>
                {
                    b.Property<long>("ColetaId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("TipoResiduoId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("ColetaId", "TipoResiduoId");

                    b.HasIndex("TipoResiduoId");

                    b.ToTable("ColetaTipoResiduo");
                });

            modelBuilder.Entity("EcoClean.Models.EnderecoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Complemento")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DATE");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<int>("Numero")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE");

                    b.HasKey("Id");

                    b.ToTable("Endereco", (string)null);
                });

            modelBuilder.Entity("EcoClean.Models.MoradorModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<long>("EnderecoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Morador", (string)null);
                });

            modelBuilder.Entity("EcoClean.Models.NotificacaoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime?>("DataEnvio")
                        .HasColumnType("DATE");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.HasKey("Id");

                    b.ToTable("Notificacao", (string)null);
                });

            modelBuilder.Entity("EcoClean.Models.RotaEnderecoModel", b =>
                {
                    b.Property<long>("EnderecoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("RotaId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("EnderecoId", "RotaId");

                    b.HasIndex("RotaId");

                    b.ToTable("RotaEndereco");
                });

            modelBuilder.Entity("EcoClean.Models.RotaModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DATE");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE");

                    b.HasKey("Id");

                    b.ToTable("Rota", (string)null);
                });

            modelBuilder.Entity("EcoClean.Models.TipoResiduoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DATE");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATE");

                    b.HasKey("Id");

                    b.ToTable("TipoResiduo", (string)null);
                });

            modelBuilder.Entity("EcoClean.Models.ColetaModel", b =>
                {
                    b.HasOne("EcoClean.Models.CaminhaoModel", "Caminhao")
                        .WithMany()
                        .HasForeignKey("CaminhaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoClean.Models.EnderecoModel", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoClean.Models.RotaModel", "Rota")
                        .WithMany()
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caminhao");

                    b.Navigation("Endereco");

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("EcoClean.Models.ColetaTipoResiduoModel", b =>
                {
                    b.HasOne("EcoClean.Models.ColetaModel", "Coleta")
                        .WithMany("ColetaTipoResiduo")
                        .HasForeignKey("ColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoClean.Models.TipoResiduoModel", "TipoResiduo")
                        .WithMany("ColetaTipoResiduo")
                        .HasForeignKey("TipoResiduoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coleta");

                    b.Navigation("TipoResiduo");
                });

            modelBuilder.Entity("EcoClean.Models.MoradorModel", b =>
                {
                    b.HasOne("EcoClean.Models.EnderecoModel", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("EcoClean.Models.RotaEnderecoModel", b =>
                {
                    b.HasOne("EcoClean.Models.EnderecoModel", "Endereco")
                        .WithMany("RotaEndereco")
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoClean.Models.RotaModel", "Rota")
                        .WithMany("RotaEndereco")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("EcoClean.Models.ColetaModel", b =>
                {
                    b.Navigation("ColetaTipoResiduo");
                });

            modelBuilder.Entity("EcoClean.Models.EnderecoModel", b =>
                {
                    b.Navigation("RotaEndereco");
                });

            modelBuilder.Entity("EcoClean.Models.RotaModel", b =>
                {
                    b.Navigation("RotaEndereco");
                });

            modelBuilder.Entity("EcoClean.Models.TipoResiduoModel", b =>
                {
                    b.Navigation("ColetaTipoResiduo");
                });
#pragma warning restore 612, 618
        }
    }
}
